<?php

/**
 * lyMediaAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class lyMediaAssetTable extends PluginlyMediaAssetTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object lyMediaAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('lyMediaAsset');
    }
}