<?php

/**
 * BaselyMediaFolder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property clob $description
 * @property string $relative_path
 * @property Doctrine_Collection $Assets
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method clob                getDescription()   Returns the current record's "description" value
 * @method string              getRelativePath()  Returns the current record's "relative_path" value
 * @method Doctrine_Collection getAssets()        Returns the current record's "Assets" collection
 * @method lyMediaFolder       setId()            Sets the current record's "id" value
 * @method lyMediaFolder       setName()          Sets the current record's "name" value
 * @method lyMediaFolder       setTitle()         Sets the current record's "title" value
 * @method lyMediaFolder       setDescription()   Sets the current record's "description" value
 * @method lyMediaFolder       setRelativePath()  Sets the current record's "relative_path" value
 * @method lyMediaFolder       setAssets()        Sets the current record's "Assets" collection
 * 
 * @package    ptsf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaselyMediaFolder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ly_media_folder');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('relative_path', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('lyMediaAsset as Assets', array(
             'local' => 'id',
             'foreign' => 'folder_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
    }
}