<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/11 18:26:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:///C:\\wamp\\www\\sf_play_ground\\ptsf\\data/ptsf.sqlite',
  'name' => 'doctrine',
)),);
