<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/14 15:13:17
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'ptsf',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_categories' => array (
  'Utilisateurs' => 
  array (
    'items' => 
    array (
      'utilisateurs' => 
      array (
        'url' => 'guard_user',
      ),
      'groupes' => 
      array (
        'url' => 'sf_guard_group',
      ),
    ),
  ),
  'Medias' => 
  array (
    'items' => 
    array (
      'gestion' => 
      array (
        'url' => 'ly_media_asset',
      ),
    ),
  ),
),
  'app_sf_media_browser_root_dir' => '/uploads',
  'app_sf_media_browser_thumbnails_enabled' => false,
  'app_sf_media_browser_thumbnails_dir' => '.thumbnails',
  'app_sf_media_browser_thumbnails_max_width' => 64,
  'app_sf_media_browser_thumbnails_max_height' => 64,
  'app_sf_media_browser_assets_list' => array (
  'js' => NULL,
  'css' => 
  array (
    0 => '/sfMediaBrowserPlugin/css/list.css',
  ),
),
  'app_sf_media_browser_assets_widget' => array (
  'js' => 
  array (
    0 => '/sfMediaBrowserPlugin/js/WindowManager.js',
    1 => '/sfMediaBrowserPlugin/js/form_widget.js',
  ),
  'css' => 
  array (
    0 => '/sfMediaBrowserPlugin/css/form_widget.css',
  ),
),
  'app_sf_media_browser_file_types' => array (
  'document' => 
  array (
    'extensions' => 
    array (
      0 => 'doc',
      1 => 'xls',
      2 => 'xcf',
      3 => 'ai',
    ),
    'icon' => 'doc',
  ),
  'image' => 
  array (
    'extensions' => 
    array (
      0 => 'png',
      1 => 'jpg',
      2 => 'jpeg',
      3 => 'gif',
    ),
  ),
  'pdf' => 
  array (
    'extensions' => 
    array (
      0 => 'pdf',
    ),
  ),
  'bin' => 
  array (
    'extensions' => 
    array (
      0 => 'bin',
      1 => 'exe',
      2 => 'sh',
      3 => 'bat',
      4 => 'deb',
      5 => 'yum',
    ),
  ),
  'video' => 
  array (
    'extensions' => 
    array (
      0 => 'wmv',
      1 => 'avi',
      2 => 'mpg',
      3 => 'mpeg',
      4 => 'flv',
      5 => 'mp4',
    ),
  ),
  'audio' => 
  array (
    'extensions' => 
    array (
      0 => 'ogg',
      1 => 'mp3',
      2 => 'flac',
      3 => 'wma',
      4 => 'cda',
    ),
  ),
  'text' => 
  array (
    'extensions' => 
    array (
      0 => 'txt',
    ),
  ),
  'tarball' => 
  array (
    'extensions' => 
    array (
      0 => 'tar',
      1 => 'gz',
      2 => 'zip',
      3 => 'bzip',
      4 => 'gzip',
      5 => 'rar',
      6 => '7z',
    ),
  ),
),
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
),
  'app_lyMediaManager_use_i18n' => true,
  'app_lyMediaManager_i18n_cultures' => array (
  'en' => 'English',
  'fr' => 'Francais',
),
));
